feat: Integration weez (#2719)
* feat: implement change

* add local keycloak

* review

* feat: Upgrade Next version (#2713)

* update next version

* fix: failed run

* review

* fix: error due to next last version

* add secrets

* update kontinuous

* update proconnect url

* chore: update configs

* fix: config

* fix: config file error

* chore: remove redis

* Revert "chore: remove redis"

This reverts commit 99e6a1be4dd453d62e8baf844e5440d12d3f0201.

* fix: update redis docker image

* add env

* chore: config

* chore: config

* fix: config

* config

* config

* config

* config

* config

* config

* config

* config

* add jwks config

* fix: simplify userinfo config to let NextAuth handle JWT automatically

* fix: jwks

* feat: add log proconnect info

* fix: error

* test

* fix

* fix

* import crypto

* fetch user info

* log user info

* fix: userinfo

* remove crypto

* fix

* fix: temps expiration

* fix

* fix: userinfo

* config logout

* update logout

* force account selection

* fix: error

* clean moncomptepro

* fix: TU failed

* revert sealed-secret

* fix: local login

* organization data

* fix: proconnect recuperation du siret

* adapt realm-export

* update realm

* fix local keycloak

* feat: integration api weez

* remove company related parts from repeq

* design

* clean

* Revert "clean"

This reverts commit 54ab7b093a6a4e116e6eb1fc68be5d5543692b45.

* refactor: clean

* fix: pipeline

* fix: pipeline

* fix: commencer next step

* fix: build

* fix: lock

* dev

* remove redis + fix build

* save

* fix: build error

* fix: build

* fix: icons + deploy

* ajout package require-in-the-middle

* fix: deploy

* fix: proconnect url

* update proxy

* clean package

* fix: deploy

* fix: deploy

* fix: remove redis

* fix: deploy failure

* fix: deploy

* Remove Redis configuration and disable Redis instrumentation

* Remove Redis environment variables and disable instrumentation

* Disable OpenTelemetry instrumentation to fix Redis module loading error

* fix: turbopack

* fix: turbopack

* fix: build

* fix: icon dsfr

* feat: ajout de weez api dans l'api actuel de recherche entreprise

* refactoration api weez

* fix: entreprise api

* fix: entreprise on repeq

* fix: declaration transmission

* fix: ts

* fix: redirection failure repeq

* dummy commit

* Revert "dummy commit"

This reverts commit e54a228a44bc1744c4d8c3eb7f6d51fa08a686d8.

* remove siren validation

* Revert "remove siren validation"

This reverts commit a49f4cfa61b06b40bf58efb410e4749e2643bd69.

* fix: try env

* Revert "fix: try env"

This reverts commit f77a73447ace7fbaaa47c0ceeed24bd54707b030.

* fix: config env

* Revert "fix: config env"

This reverts commit ca21e15f82299b5bd2980ce4ef41c944dad1b1e0.

diff --git a/packages/app/Dockerfile b/packages/app/Dockerfile
--- a/packages/app/Dockerfile
+++ b/packages/app/Dockerfile
@@ -43,7 +43,14 @@ ENV GENERATE_SOURCEMAP=true \
     NODE_ENV=production
 
 # Clean output directory and build with source maps
-RUN --mount=type=secret,id=sentry_auth_token export SENTRY_AUTH_TOKEN=$(cat /run/secrets/sentry_auth_token); \
+RUN --mount=type=secret,id=sentry \
+    if [ "$NEXT_PUBLIC_EGAPRO_ENV" = "production" ]; then \
+        if [ ! -f /run/secrets/sentry ]; then \
+            echo "Sentry secret required for production build" >&2; \
+            exit 1; \
+        fi; \
+        export SENTRY_AUTH_TOKEN=$(grep '^SENTRY_AUTH_TOKEN=' /run/secrets/sentry | cut -d'=' -f2); \
+    fi; \
     export NODE_OPTIONS="--max-old-space-size=8192"; \
     export GENERATE_SOURCEMAP=true; \
     export SENTRY_ALLOW_FAILURE=true; \
